### ISSUE TITLE
Add/Update unit tests across the codebase

### ISSUE THREAD

**Issue by collectedmind** [Pocket/extension-save-to-pocket#10]
## Expected Behavior

Unit tests should be present for all applicable code

## Actual Behavior

Minimal unit tests are available at this time

## Specifications

* Version: 3.0.0
* Browser: ALL
* Operating System:ALL

**Comment by anthony-liddle** [comment]
This ticket is incredibly old. While we need unit tests, we don't currently have the bandwidth to prioritize writing them. Closing this ticket until we've had a chance to re-evaluate this need.
