### ISSUE TITLE
refactor(styles): move from sass to css in js

### ISSUE THREAD

**Issue by stephshelley** [Pocket/extension-save-to-pocket#102]
## Acceptance Criteria
- Components should render properly with injected stylesheets in both Chrome and Safari
- Sass should be removed completely.

**Comment by nelsonomuto** [comment]
Gonna break this down into a few steps:

- [x] set up emotion 
- [-] strategy for migrating mixins and shared variables/styles
- [ ] add storybooks for react components 
- [ ] test and verify in chrome 

I had to upgrade react to get emotion working in storybooks FYI https://github.com/storybookjs/storybook/issues/4796 

Right now I'm working through a few strategies to see how to best perform this task, my initial thought was that we can easily just inject the styles that we had globally via emotion's inject API but the styles have a lot of dependencies on mixins and variables so I'm looking at ways of handling this. I'm debating between using an `elements` file/folder approach and inlining the emotion components and styles in the components themselves.
