### ISSUE TITLE
feat(safari): Implement macOS launcher screen

### ISSUE THREAD

**Issue by stephshelley** [Pocket/extension-save-to-pocket#111]
## Acceptance Criteria
- The macOS launcher app should reflect the designs [here](https://www.figma.com/file/eDzQmnz0uIAgsrv8a3QBky/Safari-12-App-Launcher?node-id=63%3A2&viewport=849%2C681%2C1).
- When a user hits the Enable button, the app is enabled.
- When a user clicks the "Need help?" link, it should open https://help.getpocket.com/article/1042-using-pocket-for-safari

[assets.zip](https://github.com/Pocket/extension-save-to-pocket/files/3553773/assets.zip)

**Comment by nzeltzer** [comment]
https://help.getpocket.com/article/1042-using-pocket-for-safari
