### ISSUE TITLE
Add Storybooks for components 

### ISSUE THREAD

**Issue by collectedmind** [Pocket/extension-save-to-pocket#12]
## Expected Behavior

[Storybooks](https://storybook.js.org/) should be implemented for all ui elements.  This would be an effort to better leverage components for re-use throughout the Pocket eco-system.

## Actual Behavior

No storybooks exist at this time

## Specifications

* Version: 3.0.0
* Operating System:ALL
* Browser: ALL

**Comment by anthony-liddle** [comment]
This has been implemented as of version `4.0.0`
