### ISSUE TITLE
fix(dropdown): Dropdown menu should not persist

### ISSUE THREAD

**Issue by stephshelley** [Pocket/extension-save-to-pocket#156]

**Comment by collectedmind** [comment]
Adjusted this functionality to match Chrome.  The dropdown actions do not close the dropdown, however the dropdown menu should not persist once the door-hanger closes.

Chrome:
![2019-09-14 08 47 01](https://user-images.githubusercontent.com/16119672/64910559-7b311f00-d6cc-11e9-87f3-9e38c4f0ad79.gif)

Safari:
![2019-09-14 08 47 51](https://user-images.githubusercontent.com/16119672/64910560-7b311f00-d6cc-11e9-8e04-02f0022c9908.gif)

**Comment by stephshelley** [comment]
Marking this as closed. Behavior matches Chrome behavior.
