### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by jjlee** [Pocket/extension-save-to-pocket#18]
## Expected Behavior

Can follow instructions to build the pocket web extension and load the resulting extension in Firefox 57 / 58 beta in order to do development on Pocket.

## Actual Behavior

I see the front-end-build-tools repo and this one (extension-save-to-pocket), but it is not clear to me how precisely to use the two repositories in order to build this extension.

## Steps to Reproduce the Problem

If I follow the docs in this repo, I get this (not to my surprise, but it's unclear to me how to use front-end-build-tools):

    me@host:~/Downloads/extension-save-to-pocket:0$ yarn start
    yarn run v1.3.2
    $ build-pocket save-to-pocket start
    module.js:538
    throw err;
    ^

    Error: Cannot find module '../extensions/save-to-pocket/scripts/start'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.resolve (internal/module.js:18:19)
    at Object.<anonymous> (/home/me/Downloads/extension-save-to-pocket/node_modules/pocket-build-tools/bin/run.js:38:19)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    error Command failed with exit code 1.
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Trying to start from front-end-build-tools instead, that repo

1. Doesn't specify what command(s) to run to build extension-save-to-pocket
1. Seems to want a particular directory structure in which extension-save-to-pocket is perhaps renamed save-to-pocket (in a directory named extensions alongside front-end-build-tools)...
1. ...but with that directory structure, it would be looking for directory `../extensions/save-to-pocket/scripts`, which does not exist.

## Specifications

* Version: git rev `8c627fec`
* Browser: I didn't get that far!  But I'm aiming to load it in Firefox 58 beta
* Operating System: Ubuntu

**Comment by collectedmind** [comment]
Hey @jjlee 

Sorry for the confusion. We will be updating this process for a bit more clarity this week.  I am also gonna take it through Firefox as well to make sure there are no additional snags.

**Comment by collectedmind** [comment]
Closing this issue as it has been addressed in the front-end-build-tools repo
