### ISSUE TITLE
Catalina Safari beta extension

### ISSUE THREAD

**Issue by Sherafgan** [Pocket/extension-save-to-pocket#187]
Hi! Could you please define status of safari "save to pocket" extension for latest safari beta? Couldn't find any way to install it. Thank you!

* Browser: Safari (beta) 13.0.1 (15608.2.11.1.1)
* Operating System: macOS Catalina 10.15 Beta (19A558d)

**Comment by collectedmind** [comment]
Hi @Sherafgan,

Apple now requires safari extensions to be bundled in an app and distributed through the App Store. We currently have a build for Safari App Extension in review with the App Store.  We will post as soon as it is clear and there is a version available for installation.

**Comment by Sherafgan** [comment]
@collectedmind Got it, thank you!
