### ISSUE TITLE
Add tag autocomplete functionality

### ISSUE THREAD

**Issue by jrochell** [Pocket/extension-save-to-pocket#198]
## Expected Behavior

While typing tags, we show a drop-down list of tag that already exist in a user account. You should be able to navigate the drop-down list with the mouse or arrow keys. Pressing `Enter` will add a highlighted tag from the drop-down and keep the window open for additional tagging.

## Actual Behavior

When typing tags, an autocomplete drop-down menu does not appear. 

## Steps to Reproduce the Problem

1. Save a page
2. Start typing a tag in the tags field

## Specifications

* Version: 1.0
* Browser: Safari 13
* Operating System: macOS 10.14.6

**Comment by Sherafgan** [comment]
Hi! Is there any progress with this issue?)

**Comment by collectedmind** [comment]
@Sherafgan Absolutely! This change has been submitted and is awaiting approval.  Hopefully, you will see it show up next week.

**Comment by Sherafgan** [comment]
Great news, thanks!

**Comment by anthony-liddle** [comment]
This has been implemented as of extension version `4.0.0`
