### ISSUE TITLE
Extend system requirements to older versions of macOS

### ISSUE THREAD

**Issue by jrochell** [Pocket/extension-save-to-pocket#199]
Our Save to Pocket extension says that it requires macOS 10.14 or later. However, Safari 12 can run on previous versions of macOS. 

This ticket is to extend support to previous versions. [See this slack thread for more info. ](https://pocket.slack.com/archives/CCRGNEGEP/p1569862914274600)

**Comment by anthony-liddle** [comment]
This is an old ticket, and most likely no longer applies given the available versions of MacOS and Safari. Closing.
