### ISSUE TITLE
Safari save-to-pocket pop-up doesn't show existing tags when user starts typing

### ISSUE THREAD

**Issue by Sherafgan** [Pocket/extension-save-to-pocket#202]
## Expected Behavior
 As in previous versions of the extension, when user clicks save-to-pocket and starts typing tags in a pop-up, already used tags like "readsoon" for other saved websites show up when user starts typing "read".

## Actual Behavior
User have to remember the exact tag he used for alike websites he/she previously saved and type that exact tag fully without a choice to choose from autocomplete options.

## Specifications
* Browser: Safari (beta) 13.0.2 (15608.2.30.1.1)
* Operating System: macOS Catalina 10.15 Beta (19A582a)

**Comment by collectedmind** [comment]
Hey @Sherafgan! 

Thanks for raising this.  We are tracking this as a fast follow in this ticket: #198.  Should be available in the next release we make.

**Comment by Sherafgan** [comment]
@collectedmind cool, thank you! closing this issue then.
