### ISSUE TITLE
pop-up is closing before completing tags

### ISSUE THREAD

**Issue by nctbrtc** [Pocket/extension-save-to-pocket#208]
## Expected Behavior
I want to add as much tag I want
## Actual Behavior
It goes away before I finish taggin
## Steps to Reproduce the Problem

When I right click on a page and click on add to pocket, the pop up opens on the top right with a box to type tags, but mostly goes away before I finish it. I want it to go away only I press enter

## Specifications

* Version: latest
* Browser: Chrome
* Operating System: Win 10

**Comment by suiluj** [comment]
yes i have the same problem since the beginning of using pocket (over a year)

It ist really frustrating!

I am using Chrome on macos.

Please fix this.

**Comment by argarner** [comment]
This has an open PR that's been sitting there for almost a year, without action. I don't know what the pocket team are up to, but they clearly aren't maintaining this extension.

https://github.com/Pocket/extension-save-to-pocket/pull/203

**Comment by suiluj** [comment]
i think this is fixed now.

**Comment by anthony-liddle** [comment]
This is fixed as of extension version `4.0.0`
