### ISSUE TITLE
Build issue 

### ISSUE THREAD

**Issue by lnfel** [Pocket/extension-save-to-pocket#218]
## Expected Behavior
Follow instructions to build the pocket web extension and load the resulting extension in Chrome Version 85.0.4183.102 (Official Build) (64-bit) in order to do development on Pocket.

## Actual Behavior
Running `npm run start` fails to compile with an error:
```
Failed to compile.
 
./_chromium/background.js
Module not found: Can't resolve 'actions' in 'C:\Sites\extension-save-to-pocket\_chromium'
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\hiberfil.sys'
```

## Steps to Reproduce the Problem

1. Clone master branch of this repo
2. Create keys.json in _chromium folder with the following:
```
{
  "Extension": "93318-XXXXXXXXXXXXXXXXX"
}
```
3. Run `npm install`
4. Run `npm run start`

## Notes
Also tried loading the resulting build in `build/_dev` to chrome extension which is obviously not working due to some errors:
```
Uncaught Error: Cannot find module 'common/interface'
[WDS] Disconnected!
```

**Comment by anthony-liddle** [comment]
The build process has been updated. I recommend trying again following the new build instructions as of extension version `4.0.0`
