### ISSUE TITLE
Opening an SVG URL shows an error in DevTools console

### ISSUE THREAD

**Issue by nevcos** [Pocket/extension-save-to-pocket#224]
## Expected Behavior

Open an SVG file in a new tab, in DevTools console there should be no errors

## Actual Behavior

When opening an SVG in new tab, a console error shows in DevTools:
```
react-dom.production.min.js:764 Uncaught TypeError: Cannot use 'in' operator to search for 'animation' in undefined
    at Be (react-dom.production.min.js:764)
    at Object.<anonymous> (react-dom.production.min.js:770)
    at n (bootstrap:19)
    at Object.<anonymous> (index.js:34)
    at n (bootstrap:19)
    at Module.<anonymous> (inject.js:2)
    at n (bootstrap:19)
    at Object.<anonymous> (inject.js:2)
    at n (bootstrap:19)
    at bootstrap:83
```

## Steps to Reproduce the Problem

1. Open Chrome with Save to Pocket extension installed
2. Open an SVG URL such as https://upload.wikimedia.org/wikipedia/commons/6/67/Firefox_Logo%2C_2017.svg
3. Open DevTools console and confirm there's an error

## Specifications

* Version: 3.1.3.0
* Browser: Chrome 91.0.4472.77
* Operating System: Windows 10

**Comment by anthony-liddle** [comment]
This no longer seems to be an issue as of extension version `4.0.0`
