### ISSUE TITLE
Add Hacker News site integration

### ISSUE THREAD

**Issue by collectedmind** [Pocket/extension-save-to-pocket#3]
## Expected Behavior

Add a Pocket button into the Hacker News feed

## Actual Behavior

Nothing is injected.  Code is incomplete

## Steps to Reproduce the Problem

1. Open HackerNews
1. Observe missing Save to Pocket

## Specifications

* Version: 3.0.0
* Browser: ALL
* Operating System:ALL

**Comment by luckman212** [comment]
Why was this removed from 3.0? It was working before...

**Comment by andrewcl** [comment]
It seems the functionality has either been broken or removed in the current release of the extension. 

Would it be possible for a contributor to look into the absence of the feature and escalate an issue if this is indeed an issue? Thanks!

**Comment by collectedmind** [comment]
This was removed in 3.0 primarily so we could revisit the functionality of all our site integrations and make sure we are providing the best experience.  This is on the radar and is gonna be added back in to a future release.

I will escalate this.

**Comment by brianyeado** [comment]
FWIW, dropping this in 3.0 completely disrupted my normal reading / saving workflow, and reduced the value I get from Pocket as a subscriber. I appreciate the need to remake site integrations, and I hope this is added back ASAP.

**Comment by colby-ham** [comment]
I agree with brianyeado, taking away these integrations has been reducing a lot of the value I get from Pocket

**Comment by anthony-liddle** [comment]
As websites continually update, it has caused any integrations to become extremely brittle. Unfortunately we don't have the bandwidth to update/add these integrations, so we've dropped all integration support as of extension version `4.0.0`. We may bring these back in the future once we've had a chance to revisit.
