### ISSUE TITLE
Update Twitter Integration

### ISSUE THREAD

**Issue by collectedmind** [Pocket/extension-save-to-pocket#33]
## Expected Behavior
1. Clicking on the pocket icon with twitter integration needs to be more clear in what function it will execute.  At present we have regressed to saving the tweet link but would like to be a bit smarter about what we are saving (saving article links, excluding hash tags for example)
2. Showing the Dropdown on a Twitter Save - At present this is disabled while we work out the above expectations.  Once it is clear we should re-enable the dropdown.

## Path Forward
Map our the supported use cases and what the expectation is for those use cases.

**Comment by anthony-liddle** [comment]
As websites continually update, it has caused any integrations to become extremely brittle. Unfortunately we don't have the bandwidth to update/add these integrations, so we've dropped all integration support as of extension version `4.0.0`. We may bring these back in the future once we've had a chance to revisit.
