### ISSUE TITLE
Reddit posts sometimes are not pocketed correctly

### ISSUE THREAD

**Issue by orschiro** [Pocket/extension-save-to-pocket#39]
Hey guys, 

Where is the right place to report a bug against Android?

1. Installed Pocket on Moto G2 with Android 6
2. Setup IFTTT trigger to send new Reddit posts to Pocket

Sometimes the posts are pocketed just fine. But sometimes they end up as follows:

![image](https://user-images.githubusercontent.com/170947/36604068-fc18f482-18bc-11e8-8d8b-98c82f45a4b2.png)

What could be the issue here?

Thanks!

**Comment by jrochell** [comment]
Hi there! Thanks for the report. 

The best place to report bugs that aren't specifically related to our extension is to [send an email to our support team](https://help.getpocket.com/contact). They're happy to help diagnose and report issues to our team.
