### ISSUE TITLE
Add Reddit site integration

### ISSUE THREAD

**Issue by collectedmind** [Pocket/extension-save-to-pocket#4]
## Expected Behavior

Add a Pocket button into the Reddit feed

## Actual Behavior

Nothing is injected.  Code is incomplete

## Steps to Reproduce the Problem

1. Open Reddit
1. Observe missing Save to Pocket

## Specifications

* Version: 3.0.0
* Browser: ALL
* Operating System:ALL

**Comment by luckman212** [comment]
Why was this removed from 3.0? It was working before...

**Comment by collectedmind** [comment]
Hey @luckman212,

We removed this temporarily in order to be sure we are providing the most value with our site integrations.  We will be revisiting and re-adding site integrations ASAP.  See https://github.com/Pocket/extension-save-to-pocket/issues/3

**Comment by anthony-liddle** [comment]
As websites continually update, it has caused any integrations to become extremely brittle. Unfortunately we don't have the bandwidth to update/add these integrations, so we've dropped all integration support as of extension version `4.0.0`. We may bring these back in the future once we've had a chance to revisit.
