### ISSUE TITLE
Chrome Canary | Debugging smoothness via chrome devtools

### ISSUE THREAD

**Issue by nelsonomuto** [Pocket/extension-save-to-pocket#58]
## Expected Behavior
While debugging on the chrome devtools, setting up breakpoints there should not be much slowness when stepping through code or resuming code execution.

This issue is not present in the stable Chrome version.
TODO: investigate in Safari, Edge, Yandex etc.

>I'm assuming we can tweak webpack source map settings to fix this, otherwise it might just be a bug for Canary to resolve that's causing this.

## Actual Behavior
The browser seems stuck when a breakpoint is hit, there is a lot of lag and sometimes only closing the background inspector seems to resume script execution. This presents a poor experience for debugging during development.

## Steps to Reproduce the Problem

1. Run the code locally
1. Load the unpacked extension
1. Open the background inspector in chrome
1. Set a breakpoint on line 123 of background.js (see attached)
1. Click the extension badge to trigger save so the breakpoint is hit

## Specifications

* Version: save-to-pocket@1.0.0 (via package.json)
* Browser: Chrome Canary Version 69.0.3475.0 
* Operating System: macOS 10.13.5

<img width="1073" alt="screen shot 2018-06-28 at 2 33 47 pm" src="https://user-images.githubusercontent.com/1546207/42061877-7a42cef2-7ae0-11e8-83ab-2588b5d4c303.png">

**Comment by collectedmind** [comment]
We are going to remove the external build dependency with the restructure in #55, so it should be easier to tweak the web pack build and improve the experience.

**Comment by anthony-liddle** [comment]
This ticket is old and no longer applies to the current build system.
