### ISSUE TITLE
Add feedback during/after tag syncing

### ISSUE THREAD

**Issue by collectedmind** [Pocket/extension-save-to-pocket#6]
## Expected Behavior

When adding tags there should be some feedback when tags sync with the server

## Actual Behavior

No visual feedback during or after sync

## Steps to Reproduce the Problem

1. Save a page to Pocket
1. Add tags to the page
1. Observe the lack of visual feedback

## Specifications

* Version: 3.0.0
* Browser: ALL
* Operating System:ALL

**Comment by anthony-liddle** [comment]
This was implemented in extension version `4.0.0`
