### ISSUE TITLE
Vivaldi browser crashing when save to pocket extension is clicked

### ISSUE THREAD

**Issue by nelsonomuto** [Pocket/extension-save-to-pocket#69]
## Expected Behavior
Pocket extension works without the browser crashing
## Actual Behavior
Upon clicking the extension, the browser crashes 
<img width="441" alt="screen shot 2019-01-08 at 1 42 23 pm" src="https://user-images.githubusercontent.com/1546207/50913870-5a108400-1403-11e9-839a-8c5459d5aa57.png">

## Steps to Reproduce the Problem
1. Download vivaldi browser
1. Install pocket extension
1. Click pocket extension

## Specifications
* Version: 3.0.5.2
* Browser: Vivaldi 2.2.1388.37 (Stable channel) (64-bit)
* Operating System: macOS 10.14.2 (Note: The problem occured with prior versions as well.)

**Comment by drahnieR** [comment]
This seems to be a browser bug. And it's fixed in the latest release of Vivaldi.

In their [latest release notes](https://vivaldi.com/blog/auto-stacking-tabs/).

> [Mac] Clicking certain extension icons makes Vivaldi crash (VB-44298)

**Comment by nelsonomuto** [comment]
Very nice @drahnieR thanks for the update! I just verified this is fixed for me as well now.
