### ISSUE TITLE
Add most used tags feature

### ISSUE THREAD

**Issue by BenSchZA** [Pocket/extension-save-to-pocket#78]
## Expected Behavior

When adding a new page to Pocket, instead of entering in the tag, there should also be a list of most used tags that can be selected. I often finding myself forgetting what tags I previously used, and there's no quick and easy way to see that.

## Actual Behavior

Tag entry box with no smart features for suggesting etc.

## Next Steps

I'm happy to contribute. I'm familiar with React-Redux stack.

## Specifications

* Version: Built in to Firefox, see below
* Browser: Firefox Quantum 66.0.2 64 bit
* Operating System: NixOS

**Comment by BenSchZA** [comment]
I see this extension is native to Mozilla and should probably be logged on their Bugzilla page? Is that correct?

**Comment by nelsonomuto** [comment]
@BenSchZA  it is good you logged this here as well as we can use this to improve our offering for the chromium browsers. The extension works across chromium browsers as well.

@BenSchZA also feel free to contribute, make sure to work against the `develop` branch - I will update our contribution guidelines to indicate this

**Comment by jrochell** [comment]
Hi Ben,

Thanks for opening this issue. This repo is for our Chromium-based extensions, so you’re correct that any issues discovered with the Pocket integration in Firefox would be best posted in [Bugzilla](https://bugzilla.mozilla.org). 

That said, if you find any issues or would like to contribute to our Chromium project, this is the right place.

Regarding your suggestion, we can understand how displaying your most used tags could make tagging more efficient and help you remember what tags you’ve already used. We’re already tracking this request internally, and I’ve added your vote for this request.

If you have any additional feature ideas, please feel free to to [share them with the Pocket Support team](https://getpocket.com/contact_support), who is in charge of tracking them.
