### ISSUE TITLE
Add experiment harness

### ISSUE THREAD

**Issue by collectedmind** [Pocket/extension-save-to-pocket#8]
## Expected Behavior

Experiments should be easily added and removed from the codebase without
getting entangled with the core code.  Ultimately, we should only merge proven
experiments into the core code, at which point we assess optimizations and implementations.  

Having a system in place that let's us launch production code with an experiment and have it properly documented and tagged is also necessary.

## Actual Behavior

No such harness is in place

## Specifications

* Version: 3.0.0
* Operating System:ALL
* Browser: ALL

**Comment by anthony-liddle** [comment]
This ticket is incredibly old. While having a system in place to run A/B tests would be helpful, there aren't any of these plans on the horizon. Closing this ticket until we've had a chance to re-evaluate this need.
