### ISSUE TITLE
Use updated icon in Twitter integration

### ISSUE THREAD

**Issue by collectedmind** [Pocket/extension-save-to-pocket#82]
## Expected Behavior
Save to Pocket functionality is represented by the outlined icon to help with accessibility.  This also is a better match to Twitters current iconography.

## Actual Behavior
We are still using the solid icon during twitter integration.

Note: Twitter integration seems to be broken in the latest release

## Specifications

* Version: 3.0.6.4
* Browser: Chrome
* Operating System: OSX

**Comment by anthony-liddle** [comment]
The twitter integration has been removed as of extension version `4.0.0`
