### ISSUE TITLE
Check for resolvedID prior to making a feed request

### ISSUE THREAD

**Issue by collectedmind** [Pocket/extension-save-to-pocket#83]
When making a request for onSave recommendations we should first ensure that there is a resolvedID.  If it does not exist, no recommendationss will be returned and the request will 404.  Might as well check on the client side to reduce load and errors.

https://github.com/Pocket/extension-save-to-pocket/blob/bd871f7b0df8ebd85b16d9a63cc277157c446a9d/src/containers/save/recommendations/_recommendations.js#L165-L168

**Comment by jonathankoren** [comment]
@jonathankoren so i can watch this

**Comment by anthony-liddle** [comment]
We have dropped on save recommendations as of version `4.0.0`
