### ISSUE TITLE
Extension icon is hard to see in dark mode

### ISSUE THREAD

**Issue by vincentfiestada** [Pocket/extension-save-to-pocket#85]
## Expected Behavior

When the browser's dark mode/theme is activated, the "Save to Pocket" icon should switch to a lighter variant for better visibility.

## Actual Behavior

In dark mode, the "Save to Pocket" icon stays the same and is difficult to see against the dark background.

## Steps to Reproduce the Problem

1. Install the extension
2. Activate dark mode 

![image](https://user-images.githubusercontent.com/5321175/60319851-5faa5800-99aa-11e9-82e1-51bc00239484.png)

## Specifications

* Version: 3.0.6.4
* Browser: Microsoft Edge v77.0.197.1 (Official build) Dev (64-bit)
* Operating System: macOS Mojave v10.14.5

**Comment by nelsonomuto** [comment]
We have a fix implemented in v3.0.6.5 of save to pocket that depends on [prefers color scheme](https://caniuse.com/#feat=prefers-color-scheme) api which let's us know the user's system preference for dark/light mode.

Chrome will support this api later this month once the next version of chrome (v76) is released. However it is possible to test with v3.0.6.5 in Canary right now.
https://www.chromestatus.com/feature/5109758977638400

**Comment by nelsonomuto** [comment]
This is supported in Chrome's current version
Version 76.0.3809.132 (Official Build) (64-bit)
