### ISSUE TITLE
Define Safari App Extension Swift API requirements 

### ISSUE THREAD

**Issue by nelsonomuto** [Pocket/extension-save-to-pocket#88]
# Expected Behavior
There should be explicit requirements of API that cannot be supported in Safari and that should be accessed via swift.

## Interface requirements 
We need to address 3 major areas
#### executeScript
- signal to execute a javascript file
- this may be tricky as apple wants us to preload all extension scripts now so it may require refactoring the scripts so that they are not executed upon loading or creating variants with this behavior so that they only execute a function when manually triggered
#### openBackgroundTab
- used for login and authentication
#### closeTab
- a way to close a tab; after logging in, close the login tab
#### setToolbarIcon
- a way to update the toolbar icon
- we need this API so we can switch the toolbar icon when the user makes a save, when the user saves to pocket, we need to switch to the red icon
- for dark mode vs light mode based on the user's system preference

### 2. tab events
1. onTabCreated
1. onTabUpdate
1. onTabActivated
1. onTabRemoved
1. onTabReplaced
#### tab event details
The event should have an object passed with tab details such as:
1. tabId
1. url
1. selected/highlighted/active
1. status (loading or completed loading)

### 3. API calls
- a means of making api calls *and receive responses* for the following
1. save to pocket
1. save tags
1. fetch recommended tags
1. fetch tags
 - @nzeltzer to provide an api that accepts a url and an object, for example if I need to make a POST call, I call Nik's api and provide him a url, parameter objects and xhr method (POST/GET) and he constructs the xhr call based on this, makes the call and returns me the response body and response status

### 4. Cookies
We need a way to identify cookies set in the browser for any base url. Something similar to `chrome.cookies` API https://developer.chrome.com/extensions/cookies 

#### a) options page - TODO: frontend will handle
- How will we be able to handle an options page, based on my last discussion with @nzeltzer on this we did not see a way how this could be achieved in Safari 12. Additional research is required for this.

- ~Needs investigation on how to open a new tab to display the options page~
- ~We may display the options in a modal instead of a separate html page~
- The team has suggested using the mac app or launcher for the options settings

#### b) onUpdateAvailable
- how to handle updating and reloading the extension

#### c) Right-click context menu
- Display extension icon and label for "Save to Pocket" which when clicked triggers the extension

#### d) Keyboard shortcuts
- Triggering the extension via keyboard shortcuts: Ctrl+Shift+P (Windows), Command+Shift+P (Mac)

```
# Actual Behavior
Extension not working in safari.

# Steps to Reproduce the Problem
N/A

# Specifications

* Version: Save To Pocket v3.0.6.5
* Browser: Safari
* Operating System: Mac OS Mojave 10.14.5

**Comment by nzeltzer** [comment]
@here Just checking in to let y’all know that I’ve been actively working on the Swift API bridge as outlined in Nelson’s Github issue (https://github.com/Pocket/extension-save-to-pocket/issues/88)

Here’s a brief update on where I’m at:

💚 `executeScript` (possible; in process—may need some more guidance once I get a little deeper into it)
💚 `openBackgroundTab` (done—can pass in an arbitrary url string)
🔶 `closeTab` (possible)—we can close a tab; it appears that we can close an arbitrary tab; would be useful to know what parameters we want to pass to this method (i.e., do we want to close the active tab, or do we want the ability to close a _specific_ tab?)
🔶  `setToolbarIcon` (impossible; not clear on why we need this—if it’s for theming on dark/light theme, there are better ways to do this)
🖤  `tab events` (impossible from the Swift side—there may be Javascript callbacks, but I haven’t investigated yet)
💚  `API calls` (possible; in progress—I am writing a basic API client that will allow you to pass in a JSON object with `url`, `method`, `callback` and `parameters` fields. The JSON response, HTTP status code, etc will be passed back to the `callback` function).

**Comment by nzeltzer** [comment]
Update on `executeScript`. It looks like we'll need to take the refactor approach: I've been unable to load a script by any means other than the one you described initially.

**Comment by nzeltzer** [comment]
However, there is this: https://developer.apple.com/documentation/safariservices/safari_app_extensions/safari_app_extension_info_property_list_keys/about_permissions_for_scripts_and_style_sheets?language=objc

**Comment by nzeltzer** [comment]
Update on `setToolbarIcon`. If it was our intent to use this to transition between light/dark themes on macOS, we can drop this requirement: Safari will automatically invert the extension's icon from black-on-white to white-on-black when the system transitions—it's a freebee.

**Comment by nzeltzer** [comment]
Update on `closeTab`. I've added a function that will close the tab for the active page. `safari.extension.dispatchMessage('closeTab')`. 

If we want to close a specific tab, we'll need to agree on some specific identifier (e.g., page URL) to match the tab we want to close against all others. (But, note, identifiers like URL are not guaranteed to be unique across multiple tabs).

**Comment by nelsonomuto** [comment]
@nzeltzer do we have a way to update the toolbar icon? 
> setToolbarIcon
a way to update the toolbar icon, for dark mode vs light mode based on the user's system preference

**Comment by nzeltzer** [comment]
@nelsonomuto I don’t believe there’s a way to do this programatically. This is for Dark Mode on Mojave+? 

If so, might be worth verifying that the toolbar icon doesn’t invert automatically.

**Comment by nelsonomuto** [comment]
@nzeltzer that's only one of the use cases, we also need this API so we can switch the toolbar icon when the user makes a save, when the user saves to pocket, we need to switch to the red icon

**Comment by nelsonomuto** [comment]
@nzeltzer also one more thing that I overlooked was a way to retrieve cookies for session management, we need a way to get cookies created under the base url https://getpocket.com/ after the user has logged in I added this as 
> 4. Cookies
We need a way to identify cookies set in the browser for any base url. Something similar to chrome.cookies API https://developer.chrome.com/extensions/cookies

**Comment by nelsonomuto** [comment]
@nzeltzer also 

#### c) Right-click context menu
- Display extension icon and label for "Save to Pocket" which when clicked triggers the extension

#### d) Keyboard shortcuts
- Triggering the extension via keyboard shortcuts: Ctrl+Shift+P (Windows), Command+Shift+P (Mac)

**Comment by nzeltzer** [comment]
> @nzeltzer that's only one of the use cases, we also need this API so we can switch the toolbar icon when the user makes a save, when the user saves to pocket, we need to switch to the red icon

@nelsonomuto This looks doable. What would you like as far as an API is concerned?

Is the ability to pass in an image name sufficient?
