### ISSUE TITLE
New Twitter - save article in tweet with an article

### ISSUE THREAD

**Issue by nelsonomuto** [Pocket/extension-save-to-pocket#89]
## Expected Behavior
The way the injected button _should_ work is:

• When the tweet includes a link, the link is saved to Pocket
• When the tweet does not include a link, the tweet itself is saved to Pocket.

### tweet attribution
There’s also tweet attribution - when you save a link from twitter, we should include the tweet info along with the save so that we can display attribution in our iOS and Android apps. You’d save a link from twitter and open the link on iOS or Android. If saved from Twitter, the tweet attribution panel would show.

![IMG_0BDF323A5E82-1](https://user-images.githubusercontent.com/1546207/61393030-1dc84f80-a88e-11e9-813f-3412bf84398f.jpeg)

## Actual Behavior
https://twitter.com/aBigMess/status/1151280482946113536 
• When the tweet includes a link, pocket is saving the tweet and not the article

## Steps to Reproduce the Problem

1. Save a tweet with an article to pocket
1. Verify that the article was saved in your pocket list
1. It shows the tweet and not the article linked in the tweet

## Specifications

* Version: 3.0.6.6
* Browser: Chrome
* Operating System: macOS mojave

**Comment by anthony-liddle** [comment]
As websites continually update, it has caused any integrations to become extremely brittle. Unfortunately we don't have the bandwidth to update/add these integrations, so we've dropped all integration support as of extension version `4.0.0`. We may bring these back in the future once we've had a chance to revisit.
