### ISSUE TITLE
extension_login_success not working in safari 12 

### ISSUE THREAD

**Issue by nelsonomuto** [Pocket/extension-save-to-pocket#90]
## Expected Behavior
Login via safari 12 should work similar to chrome

## Actual Behavior
When you log in the log in tab is not closed but you get a console error instead
```
[blocked] The page at https://getpocket.com/extension_login_success was not allowed to display insecure content from http://localhost:3000/sockjs-node/info?t=1565789654683.
_start — abstract-xhr.js:132
```
<img width="1278" alt="Screen Shot 2019-08-14 at 9 34 32 AM" src="https://user-images.githubusercontent.com/1546207/63025224-c0b4bf00-be76-11e9-9276-914c4fde21a9.png">

## Steps to Reproduce the Problem

1. Go to https://getpocket.com/signup?src=extension&route=/extension_login_success
1. Open developer tools to see console errors
1. Log in
1. Verify that the tab is not closed

## Specifications

* Version:
* Browser:
* Operating System:

**Comment by collectedmind** [comment]
This has been rectified
